import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anil Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <li>home</li>
          <li>about</li>
          <li>blogs</li>
          <li>contact</li>
          <li>services</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Anil Blogs</h1>

        <p className={styles.description}>
          a blog for hunting coders by a anil babu
        </p>

        <div className="blogs">
          <h1>Popular Blogs</h1>
          <div className="blogitem">
            <h3>how to learn javascript in 2022</h3>
            <p>
              javascript is languege is used to bulid logic in programming way
            </p>
          </div>
          <div className="blogitem">
            <h3>how to learn javascript in 2022</h3>
            <p>
              javascript is languege is used to bulid logic in programming way
            </p>
          </div>
          <div className="blogitem">
            <h3>how to learn javascript in 2022</h3>
            <p>
              javascript is languege is used to bulid logic in programming way
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
